app/acceso/api/urls.py
from django.urls import path,include
from .views import *
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'permisos',PermissionApiDetailView)


urlpatterns = [
    path('',include(router.urls)),
    path('permiso/', PermissionApiListView.as_view()),
    
 

]

app/acceso/urls.py
from django.urls import path, include
from .views import *

app_name = 'acceso'

urlpatterns = [

    path('usuario_list/', usuario_list, name='usuario_list'),
    path('login/', inicio, name='login'),
    path('usuario_crear/<int:id>', usuario_crear, name='usuario_crear'),
    path('acceso/', acceso, name='acceso'),
    path('logout/', logout, name='logout'),

   









    
]

app/maestro/urls.py
from django.urls import path, include
from .views import *

app_name = 'maestro'

urlpatterns = [
    path('tipo_documento_list/', tipo_documento_list, name='tipo_documento_list'),
    path('tipo_documento_crear/', tipo_documento_crear, name='tipo_documento_crear'),
    path('tipo_documento_update/<int:id>', tipo_documento_update, name='tipo_documento_update'),

    path('cargo_list/', cargo_list, name='cargo_list'),
    path('cargo_crear/', cargo_crear, name='cargo_crear'),
    path('cargo_update/<int:id>', cargo_update, name='cargo_update'),

    path('estado_civil_list/', estado_civil_list, name='estado_civil_list'),
    path('estado_civil_crear/', estado_civil_crear, name='estado_civil_crear'),
    path('estado_civil_update/<int:id>', estado_civil_update, name='estado_civil_update'),

    path('area_list/', area_list, name='area_list'),
    path('areas_crear/', areas_crear, name='areas_crear'),
    path('areas_update/<int:id>', areas_update, name='areas_update'),









    
]

controlasistencia/urls.py
from django.contrib import admin
from django.urls import path, include
from app.maestro import urls
from app.rrhh import urls
from app.acceso import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('maestro/',include('app.maestro.urls')),
    path('rrhh/',include('app.rrhh.urls')),
    path('rrhh/api/',include('app.rrhh.api.urls')),
    path('asistencia/',include('app.asistencia.urls')),
    path('acceso/',include('app.acceso.urls')),
    path('acceso/api/',include('app.acceso.api.urls')),


]

app/acceso/models.py
from django.db import models

# Create your models here.


from django.contrib.auth.models import *

# Create your models here.

class GrupoUser(models.Model):
    user = models.ForeignKey(User, models.DO_NOTHING)
    group = models.ForeignKey(Group, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)

class GrupoPermiso(models.Model):
    group = models.ForeignKey(Group, models.DO_NOTHING)
    permission = models.ForeignKey(Permission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)

class UsuarioPermiso(models.Model):
    user = models.ForeignKey(User, models.DO_NOTHING)
    permission = models.ForeignKey(Permission, models.DO_NOTHING)
    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)

app/rrhh/models.py
from django.db import models
from app.maestro.models import *
# Create your models here.
from django.contrib.auth.models import User




class Personal(models.Model):

    SEXO=[

        ('1','MASCULINO'),
        ('2','FEMENINO')

    ]

    ESTADO=[

        ('1','ACTIVO'),
        ('2','INACTIVO')


    ]

    tipo_documento=models.ForeignKey(TipoDocumento,on_delete=models.CASCADE)
    nombres=models.CharField(max_length=100)
    apellido_paterno=models.CharField(max_length=150)
    apellido_materno=models.CharField(max_length=150)
    numero_documento=models.CharField(max_length=11)
    cargo=models.ForeignKey(Cargo,on_delete=models.CASCADE)
    estado=models.CharField(max_length=1,choices=ESTADO)
    sexo=models.CharField(max_length=1,choices=SEXO)
    estadocivil = models.ForeignKey(EstadoCivil, blank=True, null=True, on_delete=models.CASCADE)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    usuario = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    telefono = models.CharField(max_length=12, blank=True, null=True)
    area=models.ForeignKey(Areas, on_delete=models.CASCADE)

    def __str__(self):

        return self.nombres + ' ' + self.apellido_paterno + ' ' + self.apellido_materno


 	
class TipoSistemaPesiones(models.Model):

	descripcion=models.CharField(max_length=120)
	abreviado=models.CharField(max_length=6)
	porcentaje=models.IntegerField()



class RolPersonal(models.Model):
    MES_CHOICE = [
        ('01', 'ENERO'),
        ('02', 'FEBRERO'),
        ('03', 'MARZO'),
        ('04', 'ABRIL'),
        ('05', 'MAYO'),
        ('06', 'JUNIO'),
        ('07', 'JULIO'),
        ('08', 'AGOSTO'),
        ('09', 'SEPTIEMBRE'),
        ('10', 'OCTUBRE'),
        ('11', 'NOVIEMBRE'),
        ('12', 'DICIEMBRE'),
    ]

    ESTADO_ROLPERSONAL= [
        ('1', 'ACTIVO'),
        ('2', 'ENVIADO'),
        ('3', 'APROBADO'),
        ('4', 'OBSERVADO'),
       
    ]

    fecha = models.DateField()
    anio = models.SmallIntegerField()
    mes = models.CharField(max_length=2, choices=MES_CHOICE)

    area = models.ForeignKey(Areas, on_delete=models.CASCADE)
    responsable = models.ForeignKey(Personal, on_delete=models.CASCADE)
    estado = models.CharField(max_length=1, choices=ESTADO_ROLPERSONAL)

    


class DetalleRol(models.Model):
    ESTADO_DETALLEROL_CHOICE = [
        ('1', 'ACTIVO'),
        ('2', 'VALIDADO EN AREA'),
        ('3', 'VALIDADO EN PERSONAL'),
        ('4', 'OBSERVADO EN PERSONAL'),
        ('5', 'ACEPTADO DIRECTOR'),
        ('6', 'OBSERVADO DIRECTOR'),

    ]
    personal = models.ForeignKey(Personal, on_delete=models.CASCADE, blank=True, null=True)
    rol = models.ForeignKey(RolPersonal, on_delete=models.CASCADE)
    estado = models.CharField(max_length=2, choices=ESTADO_DETALLEROL_CHOICE)
    observaciones = models.TextField(blank=True, null=True)
   



class DetalleRolPersonal(models.Model):

    detallerol = models.ForeignKey(DetalleRol, on_delete=models.CASCADE)
    fecha_inicio = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    fecha_fin = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    hora_inicio=models.TimeField()
    hora_fin=models.TimeField()
    turno = models.ForeignKey(Turno, on_delete=models.CASCADE)
    personal=models.ForeignKey(Personal,on_delete=models.CASCADE, blank=True,null=True)
    check=models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Detalle Rol Personal'
        verbose_name_plural = 'Detalles Roles Personales'

class TipoPermiso(models.Model):
    ESTADO=[

        ('1','ACTIVO'),
        ('2','INACTIVO')


    ]
    descripcion=models.CharField(max_length=120)
    estado=models.CharField(max_length=1,choices=ESTADO)

class DescuentoxPermiso(models.Model):
    ESTADO=[
        ('1','ACTIVO'),
        ('2','INACTIVO')


    ]
    tipo_permiso=models.ForeignKey(TipoPermiso, on_delete=models.CASCADE)
    descuento=models.DecimalField(max_digits=9,decimal_places=2)
    estado=models.CharField(max_length=1,choices=ESTADO)

class Permiso(models.Model):
    ESTADO=[
        ('1','ABIERTO'),
        ('2','CERRADO'),
    ]


    MES_CHOICE = [
        ('01', 'ENERO'),
        ('02', 'FEBRERO'),
        ('03', 'MARZO'),
        ('04', 'ABRIL'),
        ('05', 'MAYO'),
        ('06', 'JUNIO'),
        ('07', 'JULIO'),
        ('08', 'AGOSTO'),
        ('09', 'SEPTIEMBRE'),
        ('10', 'OCTUBRE'),
        ('11', 'NOVIEMBRE'),
        ('12', 'DICIEMBRE'),
    ]
   
    personal=models.ForeignKey(Personal,on_delete=models.CASCADE)
    estado=models.CharField(max_length=1,choices=ESTADO)
    mes=models.CharField(max_length=2, choices=MES_CHOICE)
    anio=models.IntegerField()
    total_permiso=models.IntegerField()
    rol=models.ForeignKey(RolPersonal,on_delete=models.CASCADE)

class DetallePermiso(models.Model):
    ESTADO=[
        ('1','PENDIENTE'),
        ('2','ACEPTADO'),
        ('3','RECHAZADO'),
        ('4','CANCELADO')
    ]
    permiso=models.ForeignKey(Permiso,on_delete=models.CASCADE)
    descripcion=models.TextField(blank=True, null=True)
    fecha_permiso=models.DateField()
    fechahora_registro=models.DateTimeField(auto_now=True)
    


class Remuneracion(models.Model):

    ESTADO=[

        ('1','APERTURADO'),
        ('2','CERRADO')


    ]

    personal=models.ForeignKey(Personal,on_delete=models.CASCADE)
    sueldo_bruto= models.DecimalField(max_digits=9,decimal_places=3)
    fecha_inicio=models.DateField()
    fecha_fin=models.DateField(blank=True, null=True)
    estado=models.CharField(max_length=1,choices=ESTADO)
    fecha_registro=models.DateField(auto_now=True)


class DetalleRemuneracion(models.Model):
    tipo_sistema_pension=models.ForeignKey(TipoSistemaPesiones,on_delete=models.CASCADE)
    

app/acceso/api/views.py
from .serializers import *
from rest_framework.generics import *
from ..models import *
from django_filters.rest_framework import DjangoFilterBackend

from rest_framework import generics,viewsets

class PermissionApiListView(ListCreateAPIView):
    queryset = Permission.objects.all()
    serializer_class = PermissionSerializer

class PermissionApiDetailView(viewsets.ModelViewSet):
    queryset =  Permission.objects.all()
    serializer_class = PermissionSerializer

    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['content_type__app_label']

app/acceso/views.py
from django.shortcuts import render, redirect
from functools import wraps
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from app.rrhh.models import *
from app.acceso.models import *
from django.contrib.auth.models import *
from django.http import HttpResponse
from django.core.files.base import ContentFile
from django.contrib.auth.decorators import login_required
from functools import wraps
from django.contrib.auth.models import *
def check_group(group_name):
    def _check_group(view_func):
        @wraps(view_func)
        def wrapper(request, *args, **kwargs):
            if request.user.is_anonymous:
                return redirect('acceso:acceso')
            if not (request.user.groups.filter(name=group_name).exists() or request.user.is_superuser):
                return redirect('acceso:usuario_list')
            return view_func(request, *args, **kwargs)
        return wrapper
    return _check_group

def datosgenerales(request):
    try:
        modulo = 'acceso'
        personal = Personal.objects.get(usuario=request.user.id)
        estado = personal.estado
       
        try:
            usergrupo = GrupoUser.objects.filter(user_id=personal.usuario_id)
            
            #menu = Menu.objects.filter(grupo_id=2)
            #print(menu)
            
            contexto = {'estado': estado, 'persona': personal,'usergrupo':usergrupo,'modulo':modulo}
            
        except GrupoUser.DoesNotExist:
            pass
    except Personal.DoesNotExist:
        return HttpResponse('Logeado Pero no estas asignado como Personal')
    return contexto


def acceso(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    print(username)
    usu = auth.authenticate(request, username=username,password=password)
    if usu:
        login(request, usu)
        if request.GET.get('next', None):
            return HttpResponseRedirect(request.GET['next'])
        return redirect('rrhh:rol_list')
 
    else:
        return render(request,'acceso/login.html')

@login_required(login_url='configuracion:acceso')
def logout(request):
    auth.logout(request)
    return redirect('configuracion:acceso')


def inicio(request):

	return render(request,'acceso/login.html')



def usuario_list(request):

    personal=Personal.objects.all()

    
    contexto={'personal':personal,'datogeneral':datosgenerales(request)}
      

    return render(request,'acceso/usuario_list.html',contexto)

def usuario_crear(request, id):
    personal = Personal.objects.get(id=id)
    if request.method == 'POST':

        usuario = request.POST['usuario']
        password = request.POST['password']
        personal=Personal.objects.get(pk=id)
        try:

            usuario=User.objects.get(pk=personal.usuario_id)

            if request.POST['password'] =="":

                try:
                    usergroup = GrupoUser.objects.get(user_id=usuario.id,group_id=request.POST['grupo'])


                    return redirect('acceso:usuario_list')
                except GrupoUser.DoesNotExist:
                    usergroup=GrupoUser()
                    usergroup.user_id = personal.usuario_id
                    usergroup.group_id = request.POST['grupo']
                    usergroup.save()

                    permisos=request.POST.getlist('permiso')
                    if len(permisos)>0:
                        for p in permisos:
                            usuariopermiso = UsuarioPermiso()
                            usuariopermiso.user_id = personal.usuario_id
                            usuariopermiso.permission_id = p
                            usuariopermiso.save()

                    return redirect('acceso:usuario_list')


            else:
                usuarios = request.POST['usuario']
                password = request.POST['password']
                usuario.set_password(password)
                usuario.username = usuarios
                usuario.save()

                try:
                    usergroup = GrupoUser.objects.get(user_id=usuario.id,group_id=request.POST['grupo'])


                    return redirect('acceso:usuario_list')
                except GrupoUser.DoesNotExist:
                    usergroup=GrupoUser()
                    usergroup.user_id = personal.usuario_id
                    usergroup.group_id = request.POST['grupo']
                    usergroup.save()

                    permisos=request.POST.getlist('permiso')
                    if len(permisos)>0:
                        for p in permisos:
                            usuariopermiso = UsuarioPermiso()
                            usuariopermiso.user_id = personal.usuario_id
                            usuariopermiso.permission_id = p
                            usuariopermiso.save()

                    return redirect('acceso:usuario_list')
        except User.DoesNotExist:

            user = User.objects.create_user(usuario, '', password)
            user.first_name = ''
            user.last_name = ''
            user.save()

            personal = Personal.objects.get(id=id)
            personal.usuario_id = user.id
            personal.save()


            usergroup = GrupoUser()
            usergroup.user_id = personal.usuario_id
            usergroup.group_id = request.POST['grupo']
            usergroup.save()


            # agregar los permisos 
            permisos=request.POST.getlist('permiso')
     
            if len(permisos)>0:

                for p in permisos:

                    try:

                        permiso=Permiso.objects.get(pk=p)
                    except Permiso.DoesNotExist:
                        print(p)

                    
                    usuariopermiso = UsuarioPermiso()
                    usuariopermiso.user_id = personal.usuario_id
                    usuariopermiso.permission_id = p
                    usuariopermiso.save()




            return redirect('acceso:usuario_list')

    else:

        personal=Personal.objects.get(pk=id)
        try:

            usuario=User.objects.get(pk=personal.usuario_id)
            permisos=UsuarioPermiso.objects.filter(user_id=usuario.id)

            print(permisos)


        except User.DoesNotExist:
            usuario=""
            permisos=""
            print("no existe")
        grupo = Group.objects.all()
        return render(request, 'acceso/usuario_form.html',{'personal':personal,'usuario':usuario,'permisos':permisos, 'grupo':grupo,'datogeneral':datosgenerales(request)})



def logout(request):
    auth.logout(request)
    return redirect('acceso:acceso')

app/acceso/templates/acceso/login.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<title>Color Admin | Login Page</title>
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	
	<!-- ================== BEGIN BASE CSS STYLE ================== -->
	
	<link href="{% static "assets/plugins/jquery-ui/jquery-ui.min.css" %}" rel="stylesheet" />
	<link href="{% static "assets/plugins/bootstrap/4.1.0/css/bootstrap.min.css" %}" rel="stylesheet" />
	<link href="{% static "assets/plugins/font-awesome/5.0/css/fontawesome-all.min.css" %}" rel="stylesheet" />
	<link href="{% static "assets/plugins/animate/animate.min.css" %}" rel="stylesheet" />
	<link href="{% static "assets/css/default/style.min.css" %}" rel="stylesheet" />
	<link href="{% static "assets/css/default/style-responsive.min.css" %}" rel="stylesheet" />
	<link href="{% static "assets/css/default/theme/default.css" %}" rel="stylesheet" id="theme" />
	<!-- ================== END BASE CSS STYLE ================== -->
	
	<!-- ================== BEGIN BASE JS ================== -->
	<script src="{% static "assets/plugins/pace/pace.min.js" %}"></script>
	<!-- ================== END BASE JS ================== -->
</head>
<body class="pace-top">
	<!-- begin #page-loader -->
	<div id="page-loader" class="fade show"><span class="spinner"></span></div>
	<!-- end #page-loader -->
	
	<div class="login-cover">
	    <div class="login-cover-image" style="background-image: url(../assets/img/login-bg/login-bg-17.jpg)" data-id="login-cover-image"></div>
	    <div class="login-cover-bg"  style="background-color: #d9e0e7;"></div>
	</div>
	<!-- begin #page-container -->
	<div id="page-container" class="fade">
	    
           <div id="page-container">
        <!-- begin login -->
        <div class="login login-with-news-feed">
            <!-- begin news-feed -->
            <div class="news-feed" style="background-image: url(/static/assets/img/logo.jpeg);background-repeat: no-repeat;  background-color: black; margin-top: 2px;background-position: center">
                <div class="news-image "   ></div>
                <div class="news-caption">
                    
                    <p>
                    </p>
                </div>
            </div>
            <!-- end news-feed -->
            <!-- begin right-content -->
            <div class="right-content" style="background-color: #d9e0e7;">
                <!-- begin login-header -->
                <div class="login-header">
                    <div class="brand">
                        <b>SISTEMA DE CONTROL DE ASISTENCIA</b>
                        
                    </div>
                    <div class="icon">
                        <i class="fa fa-sign-in"></i>
                    </div>
                </div>
                <!-- end login-header -->
                <!-- begin login-content -->
                <div class="login-content" style="background-color: #d9e0e7;">
                  <form method="POST" action="{% url 'acceso:acceso' %}" class="margin-bottom-0">{% csrf_token %}
                  <div class="form-group m-b-20">
                      <input type="text" class="form-control form-control-lg"  name="username" placeholder="Usuario" required>
                  </div>
                  <div class="form-group m-b-20" style="background-color: #d9e0e7;">
                      <input type="password" class="form-control form-control-lg" name="password" placeholder="Contraseña" required>
                  </div>

                  <div class="login-buttons" style="background-color: #d9e0e7;">
                      <button type="submit" class="btn btn-primary btn-block btn-lg">Ingresar</button>
                  </div>

              </form>
                </div>
                <!-- end login-content -->
            </div>
            <!-- end right-container -->
        </div>
        <!-- end login -->
    </div>

	</div>
	<!-- end page container -->
	
	<!-- ================== BEGIN BASE JS ================== -->
	<script src="{% static "assets/plugins/jquery/jquery-3.2.1.min.js" %}"></script>
	<script src="{% static "assets/plugins/jquery-ui/jquery-ui.min.js" %}"></script>
	<script src="{% static "assets/plugins/bootstrap/4.1.0/js/bootstrap.bundle.min.js" %}"></script>
	<!--[if lt IE 9]>
		<script src="../assets/crossbrowserjs/html5shiv.js"></script>
		<script src="../assets/crossbrowserjs/respond.min.js"></script>
		<script src="../assets/crossbrowserjs/excanvas.min.js"></script>
	<![endif]-->
	<script src="{% static "assets/plugins/slimscroll/jquery.slimscroll.min.js" %}"></script>
	<script src="{% static "/assets/plugins/js-cookie/js.cookie.js" %}"></script>
	<script src="{% static "assets/js/theme/default.min.js" %}"></script>
	<script src="{% static "assets/js/apps.min.js" %}"></script>
	<!-- ================== END BASE JS ================== -->
	
	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static "assets/js/demo/login-v2.demo.min.js" %}"></script>
	<!-- ================== END PAGE LEVEL JS ================== -->

	<script>
		$(document).ready(function() {
			App.init();
			LoginV2.init();
		});
	</script>
</body>
</html>

app/acceso/templates/acceso/usuario_form.html
{% extends 'base.html' %}

{% load static %}


{% block css %}

<link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/switchery/switchery.css" %}" rel="stylesheet">

<link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet">
    
{% endblock %}

{% block content %}
    <div class="col-md-12 col-lg-12">
        

            
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    {% if areas %}
                     
                    <form method="POST" action="{% url 'maestro:areas_update' areas.id %}">
                        <h4 class="panel-title">Actualizar Usuario</h4>
                    {% else %}

                    <form method="POST" action="{% url 'acceso:usuario_crear' personal.id %}">
                        <h4 class="panel-title">Crear Usuario</h4>



                    {% endif %}

                    {% csrf_token %}
                        <div class="pull-right" style="margin-top: -12px;">
                            <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
                             
                        </div>


                </div>
                <div class="panel-body">
                    <div class="form-group row">
                        <label class="col-md-2">Personal</label>
                        <div class="col-md-2">{{personal}}</div>
                        <label class="col-md-2">Area:</label>
                        <div class="col-md-2">{{personal.area}}</div>
                        <div class="col-md-2">Estado</div>
                        <div class="col-md-2">{{personal.get_estado_display}}</div>
                       
                    </div>
                    <div class="form-group row">
                        <label class="col-md-2">Usuario</label>
                        <div class="col-md-2"><input type="text" name="usuario" value="{{usuario}}" id="id_usuario" class="form-control"></div>
                        <label class="col-md-2">Contraseña:</label>
                        <div class="col-md-2"><input type="password" name="password" id="password" class="form-control"></div>
                        <label class="col-md-2">Grupo</label>
                        <div class="col-md-2">
                            <select class="form-control" name="grupo" onchange="permission()" id="id_grupo">
                                <option>----</option>
                                {% for g in grupo %}
                                    <option value="{{g.id}}">{{g.name}}</option>
                                {% endfor %}


                            </select>
                        </div>
                       
                    </div>
                    <div class="form-group row">
                        <label class="col-md-2">Permisos</label>
                        <div class="col-md-10">
                                <select multiple="multiple" id="id_permiso" name="permiso" class="form-control">

                                    {% for p in permisos %}
                                        <option value="{{p.permission.id}}">{{p.permission}}</option>

                                    {% endfor %}
                                    

                                </select>
                        </div>

                    </div>
                    
                   

                       
                </div>
            </form>
            </div>
       
    </div>


    
{% endblock content %}

{% block scripts %}



<script src="{% static 'eigen/js/acceso.js' %}"></script>
<script src="{% static "assets/plugins/select2/dist/js/select2.min.js" %}"></script>
<script src="{% static "assets/plugins/switchery/switchery.js" %}"></script>
<script>
$('#id_permiso').select2();
</script>
{% endblock scripts %}

app/acceso/templates/acceso/usuario_list.html
{% extends 'base.html' %}

{% load static %}


{% block css %}

<link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/switchery/switchery.css" %}" rel="stylesheet">

<link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet">
    
{% endblock %}

{% block content %}
    <div class="col-md-12 col-lg-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    
                        
                        
                    
                    <h4 class="panel-title">Lista Usuario</h4>

                </div>
                <div class="panel-body">

                        <div class="table-responsive">
                            <table class="table table-condensed table-bordered table-hover dataTables-example" style="width:100%">
                                <thead>
                                    <tr>

                                        <th>#</th>
                                        <th>Persoanl</th>
                                        <th>Area</th>
                                        <th>Accion</th>

                                    </tr>
                                </thead>
                                <tbody>
                                
                                   {% for p in personal %}
                                    
                                   <tr class="gradeX">

                                    <td>{{p.id }}</td>
                                    <td>{{p}}</td>
                                    <td>{{p.area}}</td>
                                   

                                    

                                    <td class="center">
                                        <a class="btn btn-xs btn-primary" href="{% url 'acceso:usuario_crear' p.id %}" title="Editar"><i class="fas fa-lg fa-edit"></i></a>
                                           
                                    </td>


                                </tr>

                                {% endfor %}

                            </tbody>

                        </table>
                    </div>
                </div>
            </div>

    </div>

<div id="modal-dialog" class="modal fade" role="dialog">

</div>
    
{% endblock content %}

{% block scripts %}
<script src="{% static "assets/plugins/DataTables/media/js/jquery.dataTables.js" %}"></script>
<script src="{% static "assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js" %}"></script>
<script src="{% static "assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js" %}"></script>



<script>
   $(document).ready(function(){
    $('.dataTables-example').DataTable();
      
    });
</script>
{% endblock scripts %}