app/rrhh/api/urls.py
from django.urls import path,include
from rest_framework.routers import DefaultRouter

from .views import *


router = DefaultRouter()
router.register(r'rolpersonal',RolPersonalViewSet)
router.register('personal/(?P<personal_id>[^/.]+)/rol',RolPersonalDetalleRolViewSet)
router.register('personal/(?P<personal_id>[^/.]+)/rol',DetallePermisoRolViewSet)


urlpatterns = [
    path('',include(router.urls)),
    path('asistencia_control/<str:numero_documento>',ControlAsistenciaViewDetail.as_view()),

   
]

app/rrhh/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name='rrhh'

urlpatterns = [
    path('personal_list/', personal_list, name='personal_list'),
    path('personal_crear/', personal_crear, name='personal_crear'),
    path('personal_update/<int:id>', personal_update, name='personal_update'),

    path('rol_list/', rol_list, name='rol_list'),
    path('rol_crear/', rol_crear, name='rol_crear'),

    path('detalle_rol_form/<int:id>', detalle_rol_form, name='detalle_rol_form'),

    path('guardar_foto/<int:id_detalle>',guardar_foto, name='guardar_foto'),

    path('permiso_list/', permiso_list, name='permiso_list'),
    path('permiso_form/', permiso_form, name='permiso_form'),



    

]

controlasistencia/urls.py
from django.contrib import admin
from django.urls import path, include
from app.maestro import urls
from app.rrhh import urls
from app.acceso import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('maestro/',include('app.maestro.urls')),
    path('rrhh/',include('app.rrhh.urls')),
    path('rrhh/api/',include('app.rrhh.api.urls')),
    path('asistencia/',include('app.asistencia.urls')),
    path('acceso/',include('app.acceso.urls')),
    path('acceso/api/',include('app.acceso.api.urls')),


]

app/rrhh/api/models.py
from django.db import models

# Create your models here.

app/rrhh/models.py
from django.db import models
from app.maestro.models import *
# Create your models here.
from django.contrib.auth.models import User




class Personal(models.Model):

    SEXO=[

        ('1','MASCULINO'),
        ('2','FEMENINO')

    ]

    ESTADO=[

        ('1','ACTIVO'),
        ('2','INACTIVO')


    ]

    tipo_documento=models.ForeignKey(TipoDocumento,on_delete=models.CASCADE)
    nombres=models.CharField(max_length=100)
    apellido_paterno=models.CharField(max_length=150)
    apellido_materno=models.CharField(max_length=150)
    numero_documento=models.CharField(max_length=11)
    cargo=models.ForeignKey(Cargo,on_delete=models.CASCADE)
    estado=models.CharField(max_length=1,choices=ESTADO)
    sexo=models.CharField(max_length=1,choices=SEXO)
    estadocivil = models.ForeignKey(EstadoCivil, blank=True, null=True, on_delete=models.CASCADE)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    usuario = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    telefono = models.CharField(max_length=12, blank=True, null=True)
    area=models.ForeignKey(Areas, on_delete=models.CASCADE)

    def __str__(self):

        return self.nombres + ' ' + self.apellido_paterno + ' ' + self.apellido_materno


 	
class TipoSistemaPesiones(models.Model):

	descripcion=models.CharField(max_length=120)
	abreviado=models.CharField(max_length=6)
	porcentaje=models.IntegerField()



class RolPersonal(models.Model):
    MES_CHOICE = [
        ('01', 'ENERO'),
        ('02', 'FEBRERO'),
        ('03', 'MARZO'),
        ('04', 'ABRIL'),
        ('05', 'MAYO'),
        ('06', 'JUNIO'),
        ('07', 'JULIO'),
        ('08', 'AGOSTO'),
        ('09', 'SEPTIEMBRE'),
        ('10', 'OCTUBRE'),
        ('11', 'NOVIEMBRE'),
        ('12', 'DICIEMBRE'),
    ]

    ESTADO_ROLPERSONAL= [
        ('1', 'ACTIVO'),
        ('2', 'ENVIADO'),
        ('3', 'APROBADO'),
        ('4', 'OBSERVADO'),
       
    ]

    fecha = models.DateField()
    anio = models.SmallIntegerField()
    mes = models.CharField(max_length=2, choices=MES_CHOICE)

    area = models.ForeignKey(Areas, on_delete=models.CASCADE)
    responsable = models.ForeignKey(Personal, on_delete=models.CASCADE)
    estado = models.CharField(max_length=1, choices=ESTADO_ROLPERSONAL)

    


class DetalleRol(models.Model):
    ESTADO_DETALLEROL_CHOICE = [
        ('1', 'ACTIVO'),
        ('2', 'VALIDADO EN AREA'),
        ('3', 'VALIDADO EN PERSONAL'),
        ('4', 'OBSERVADO EN PERSONAL'),
        ('5', 'ACEPTADO DIRECTOR'),
        ('6', 'OBSERVADO DIRECTOR'),

    ]
    personal = models.ForeignKey(Personal, on_delete=models.CASCADE, blank=True, null=True)
    rol = models.ForeignKey(RolPersonal, on_delete=models.CASCADE)
    estado = models.CharField(max_length=2, choices=ESTADO_DETALLEROL_CHOICE)
    observaciones = models.TextField(blank=True, null=True)
   



class DetalleRolPersonal(models.Model):

    detallerol = models.ForeignKey(DetalleRol, on_delete=models.CASCADE)
    fecha_inicio = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    fecha_fin = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    hora_inicio=models.TimeField()
    hora_fin=models.TimeField()
    turno = models.ForeignKey(Turno, on_delete=models.CASCADE)
    personal=models.ForeignKey(Personal,on_delete=models.CASCADE, blank=True,null=True)
    check=models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Detalle Rol Personal'
        verbose_name_plural = 'Detalles Roles Personales'

class TipoPermiso(models.Model):
    ESTADO=[

        ('1','ACTIVO'),
        ('2','INACTIVO')


    ]
    descripcion=models.CharField(max_length=120)
    estado=models.CharField(max_length=1,choices=ESTADO)

class DescuentoxPermiso(models.Model):
    ESTADO=[
        ('1','ACTIVO'),
        ('2','INACTIVO')


    ]
    tipo_permiso=models.ForeignKey(TipoPermiso, on_delete=models.CASCADE)
    descuento=models.DecimalField(max_digits=9,decimal_places=2)
    estado=models.CharField(max_length=1,choices=ESTADO)

class Permiso(models.Model):
    ESTADO=[
        ('1','ABIERTO'),
        ('2','CERRADO'),
    ]


    MES_CHOICE = [
        ('01', 'ENERO'),
        ('02', 'FEBRERO'),
        ('03', 'MARZO'),
        ('04', 'ABRIL'),
        ('05', 'MAYO'),
        ('06', 'JUNIO'),
        ('07', 'JULIO'),
        ('08', 'AGOSTO'),
        ('09', 'SEPTIEMBRE'),
        ('10', 'OCTUBRE'),
        ('11', 'NOVIEMBRE'),
        ('12', 'DICIEMBRE'),
    ]
   
    personal=models.ForeignKey(Personal,on_delete=models.CASCADE)
    estado=models.CharField(max_length=1,choices=ESTADO)
    mes=models.CharField(max_length=2, choices=MES_CHOICE)
    anio=models.IntegerField()
    total_permiso=models.IntegerField()
    rol=models.ForeignKey(RolPersonal,on_delete=models.CASCADE)

class DetallePermiso(models.Model):
    ESTADO=[
        ('1','PENDIENTE'),
        ('2','ACEPTADO'),
        ('3','RECHAZADO'),
        ('4','CANCELADO')
    ]
    permiso=models.ForeignKey(Permiso,on_delete=models.CASCADE)
    descripcion=models.TextField(blank=True, null=True)
    fecha_permiso=models.DateField()
    fechahora_registro=models.DateTimeField(auto_now=True)
    


class Remuneracion(models.Model):

    ESTADO=[

        ('1','APERTURADO'),
        ('2','CERRADO')


    ]

    personal=models.ForeignKey(Personal,on_delete=models.CASCADE)
    sueldo_bruto= models.DecimalField(max_digits=9,decimal_places=3)
    fecha_inicio=models.DateField()
    fecha_fin=models.DateField(blank=True, null=True)
    estado=models.CharField(max_length=1,choices=ESTADO)
    fecha_registro=models.DateField(auto_now=True)


class DetalleRemuneracion(models.Model):
    tipo_sistema_pension=models.ForeignKey(TipoSistemaPesiones,on_delete=models.CASCADE)
    

app/rrhh/api/views.py
from rest_framework import viewsets
from rest_framework.response import Response
from .serializers import *
from app.rrhh.models import *
from app.asistencia.models import *
from rest_framework.decorators import action
from rest_framework import serializers, status, generics
from django.http import HttpResponse, JsonResponse
import time
import json
from datetime import datetime, date, time, timedelta
from django.utils import timezone

class RolPersonalViewSet(viewsets.ModelViewSet):

    queryset = RolPersonal.objects.all()
    serializer_class =RolPersonalSerializer


class RolPersonalDetalleRolViewSet(viewsets.ModelViewSet):

	queryset = DetalleRolPersonal.objects.all()
	serializer_class =DetalleRolPersonalSerializer

	@action(detail=True, methods=['GET'])

	def detalle_rol(self,request,pk=None,personal_id=None):

		detalle_rol=DetalleRolPersonal.objects.filter(detallerol__rol_id=pk, personal_id=personal_id)
		serializer = DetalleRolPersonalSerializer(detalle_rol,many=True)
		return Response(serializer.data,status=200)

class DetallePermisoRolViewSet(viewsets.ModelViewSet):

	queryset = DetallePermiso.objects.all()
	serializer_class =DetallePermisoSerializer

	@action(detail=True, methods=['GET'])

	def detalle_permiso(self,request,pk=None,personal_id=None):

		detalle_rol=DetallePermiso.objects.filter(permiso__rol_id=pk, permiso__personal_id=personal_id)
		serializer = DetallePermisoSerializer(detalle_rol,many=True)
		return Response(serializer.data,status=200)


class ControlAsistenciaViewDetail(generics.GenericAPIView):
	def get(self, request, *args, **kwargs):

		lista_detalle_json = []
		anio = datetime.now().strftime("%Y")
		mes  = datetime.now().strftime("%m")
		fecha_actual=datetime.now().strftime("%Y-%m-%d")

		hora_actual=datetime.now().strftime("%H:%M:%S")
		tipo_hora=datetime.now().strftime("%p")


		personal=Personal.objects.get(numero_documento=kwargs['numero_documento'])
		rol=RolPersonal.objects.get(anio=anio,mes=mes,area_id=personal.area_id)
		detalle_rol=DetalleRol.objects.get(rol_id=rol.id,personal_id=personal.id)
		objeto_detalle={}
		detalle_rol_personal=DetalleRolPersonal.objects.filter(detallerol_id=detalle_rol.id, fecha_inicio=fecha_actual)

		if detalle_rol_personal:
			
			for drp in detalle_rol_personal:

				try:
					print(drp.turno.abreviado)
					print(tipo_hora)
					if str(tipo_hora) == str(drp.turno.abreviado):

						asistencia=Asistencia.objects.get(personal_id=personal.id,fecha_asistencia=fecha_actual,estado=1)
						detalle_asistencia=DetalleAsistencia.objects.get(asistencia_id=asistencia.id)
						if detalle_asistencia.turno_id == 1:
							if str(tipo_hora) == 'PM':
								if str(hora_actual) > str(drp.hora_fin):

									detalle_new=DetalleAsistencia()
									detalle_new.asistencia_id=asistencia.id
									detalle_new.hora=hora_actual
									detalle_new.tipo_marcacion=2
									detalle_new.turno_id=drp.turno_id
									detalle_new.imagen='si se pudo'
									detalle_new.save()

									asistencia.estado=2
									asistencia.save()
									objeto_detalle["codError"] = "101"
									objeto_detalle["id_detalle"] = detalle_new.id
									objeto_detalle["hora"] = detalle_new.hora
									objeto_detalle["personal"] = personal.nombres+ ' ' + personal.apellido_paterno + ' ' +  personal.apellido_materno
									objeto_detalle["message"] = "SU SALIDA FUE MARCADA CON EXITO"

									lista_detalle_json.append(objeto_detalle)
									valores=json.dumps(lista_detalle_json)
									return HttpResponse(valores,content_type='application/json')

									

							else:
								objeto_detalle["codError"] = "102"
								objeto_detalle["message"] = "ERROR!! ... USTED ESTA DENTRO DE SU HORA DE TRABAJO"
								lista_detalle_json.append(objeto_detalle)
								valores=json.dumps(lista_detalle_json)
								return HttpResponse(valores,content_type='application/json')

								
						else:
							
							if str(hora_actual) > str(drp.hora_fin):
								detalle_new=DetalleAsistencia()
								detalle_new.asistencia_id=asistencia.id
								detalle_new.hora=hora_actual
								detalle_new.detallerolpersonal_id=drp.id
								detalle_new.tipo_marcacion=2
								detalle_new.turno_id=drp.turno_id
								detalle_new.imagen='si se pudo'
								detalle_new.save()

								asistencia.estado=2
								asistencia.save()
								objeto_detalle["codError"] = "101"
								objeto_detalle["id_detalle"] = detalle_new.id
								objeto_detalle["hora"] = detalle_new.hora
								objeto_detalle["personal"] = personal.nombres+ ' ' + personal.apellido_paterno + ' ' +  personal.apellido_materno
								objeto_detalle["message"] = "SU SALIDA FUE MARCADA CON EXITO"

								lista_detalle_json.append(objeto_detalle)
								valores=json.dumps(lista_detalle_json)
								return HttpResponse(valores,content_type='application/json')

							else:
								objeto_detalle["codError"] = "102"
								objeto_detalle["message"] = "ERROR!! ... USTED ESTA DENTRO DE SU HORA DE TRABAJO"
								lista_detalle_json.append(objeto_detalle)
								valores=json.dumps(lista_detalle_json)
								return HttpResponse(valores,content_type='application/json')
					
					else:



						objeto_detalle["codError"] = "102"
						objeto_detalle["message"] = "ERROR!! ...NO TIENE TURNO PROGRAMADO"
						lista_detalle_json.append(objeto_detalle)
						valores=json.dumps(lista_detalle_json)
						return HttpResponse(valores,content_type='application/json')	


				except Asistencia.DoesNotExist:

					print("noexiste marcada")

					if str(tipo_hora) == str(drp.turno.abreviado):

						if str(hora_actual) > str(drp.hora_inicio):
							print(hora_actual)
							print(drp.hora_inicio)
							objeto_detalle["codError"] = "103"
							objeto_detalle["message"] = "Error!!... ESTA FUERA DE RANGO "
							lista_detalle_json.append(objeto_detalle)
							valores=json.dumps(lista_detalle_json)
							return HttpResponse(valores,content_type='application/json')


							
						else:

							asistencia=Asistencia()
							asistencia.personal_id=personal.id
							asistencia.fecha_asistencia=fecha_actual
							asistencia.estado=1
							asistencia.save()

							### SE ACTUALIZA EL DetalleRolPersonal con check 1

							detallerolpersonal=DetalleRolPersonal.objects.get(pk=drp.id)
							detallerolpersonal.check=1
							detallerolpersonal.save()

							detalle_asistencia=DetalleAsistencia()
							detalle_asistencia.asistencia_id=asistencia.id
							detalle_asistencia.hora=hora_actual
							detalle_asistencia.tipo_marcacion=1
							detalle_asistencia.detallerolpersonal_id=drp.id
							detalle_asistencia.turno_id=drp.turno_id
							detalle_asistencia.imagen='hola'
							detalle_asistencia.save()
							objeto_detalle["codError"] = "101"
							objeto_detalle["id_detalle"] = detalle_asistencia.id
							objeto_detalle["hora"] = detalle_asistencia.hora
							objeto_detalle["personal"] = personal.nombres+ ' ' + personal.apellido_paterno + ' ' +  personal.apellido_materno
							objeto_detalle["message"] = "SE MARCO SU ENTRADA CON EXITO"
							lista_detalle_json.append(objeto_detalle)
							valores=json.dumps(lista_detalle_json)
							return HttpResponse(valores,content_type='application/json')
					else:

						print("fuera de rango")
		else:

			objeto_detalle["codError"] = "102"
			objeto_detalle["message"] = "ERROR!! ...NO EXISTE PROGRAMACION"
			lista_detalle_json.append(objeto_detalle)
			valores=json.dumps(lista_detalle_json)
			return HttpResponse(valores,content_type='application/json')
			
		
						



				

			# if drp.turno_id==1:

			# 	try:

			# 		asistencia=Asistencia.objects.get(personal_id=personal.id,fecha_asistencia=fecha_actual,estado=1)
					
			# 		if str(tipo_hora) != str(drp.turno.abreviado):
			# 			if str(hora_actual) > str(drp.hora_inicio):

			# 				print("USTED NO PUEDE MARCAR ESTA FUERA DE HORA")
			# 			else:
					
			# 				print("SU ASISTENCIA SE MARCO CORRECTAMENTE")


			# 	except Asistencia.DoesNotExist:

			# 		print("crear asistencia")
					





			# 	if str(tipo_hora):

			# 		print(str(tipo_hora))
			# else:

			# 	print("ddd")



			# print(str(tipo_hora))

			# if str(tipo_hora)== str(drp.turno.abreviado):
			# 	print(str(drp.turno.abreviado))

			# 	try:
			# 		asistencia=Asistencia.objects.get(personal_id=personal.id,fecha_asistencia=fecha_actual,estado=1)

			# 		if str(hora_actual) > str(drp.hora_fin):

			# 			print("SE MARCO SU SALIDA CORRECTAMENTE")
			# 		else:
			# 			print("USTED DEBE CULMINAR SU HORARIO DE TRABAJO")


			# 	except Asistencia.DoesNotExist:

			# 		asistencia=Asistencia()

			# 		if str(hora_actual) > str(drp.hora_inicio):

			# 			print("USTED NO PUEDE MARCAR ESTA FUERA DE HORA")
			# 		else:
					
			# 			print("SU ASISTENCIA SE MARCO CORRECTAMENTE")

			# else:



			# 	print("ss")






		# for d in detalle:
		# 	objeto_detalle={}
		# 	objeto_detalle["id"] = d.id
		# 	objeto_detalle["start"] = str(d.programacion_consultorio.fecha_atencion)+' '+ str((d.hora_inicio))
		# 	objeto_detalle["end"] = str(d.programacion_consultorio.fecha_atencion)+' '+ str(d.hora_fin)
		# 	objeto_detalle["title"] = str(d.paciente)
		# 	objeto_detalle["color"] =  '#3A87AD'
		# 	objeto_detalle["textColor"] = '#ffffff'
		# 	lista_detalle_json.append(objeto_detalle)
		# 	valores=json.dumps(lista_detalle_json)

		# return HttpResponse(valores,content_type='application/json')

app/rrhh/templates/rrhh/detalle_rol_form.html
{% extends 'base.html' %}

{% load static %}

    <link href="/static/jquery-ui.multidatespicker.css" rel="stylesheet">
    <link href="/static/jquery-ui.css" rel="stylesheet">
    <link href="/static/fullcalendar.min.css" rel='stylesheet' />
    <link href="/static/fullcalendar.print.min.css" rel='stylesheet' media='print' />
    <link href="/static/assets/plugins/select2/dist/css/select2.min.css" rel="stylesheet" />
{% block css %}

<link href="/static/fullcalendar.min.css" rel='stylesheet' />
<link href="/static/fullcalendar.print.min.css" rel='stylesheet' media='print' />
{% endblock %}

{% block content %}
<div class="col-md-12 col-lg-12">
    <form action="{% url 'rrhh:detalle_rol_form' rol.id %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <div class="panel panel-inverse">
                    <div class="panel-heading">
                        <input type="hidden" name="rol" id="id_rol" value="{{rol.id}}">
                        <input type="hidden" name="datos_rol" id="datos_rol">
                        <input type="hidden" id="id_personal_rol" name="id_personal_rol">
                        <div class="form-group row">
                            <div class="col-md-6">
                                 <h4 class="panel-title">Area : {{rol.area}}</h4>
                                 <h4 class="panel-title">Año : {{rol.anio}}</h4>
                            </div>
                            <div class="col-md-5">
                                
                                <h4 class="panel-title">Mes : {{rol.get_mes_display}}</h4>
                            </div>

                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="form-group row">
                            <label class="col-md-12">Turno</label>

                        </div>
                        <div class="form-group row">
                           <div class="col-md-12">
                            <select class="form-control" id="id_turno" name="turno">
                                    
                                {% for t in turno %}
                                <option value="{{t.id}}">{{t.descripcion}}({{t.hora_inicio}}-{{t.hora_fin}})</option>

                                {% endfor %}

                            </select>
                           </div>

                        </div>
                        <div class="form-group row">
                            <label class="col-md-12">Personal</label>

                        </div>
                        <div class="form-group row">
                            <div class="col-md-12">

                              <select id="id_personal" name="personal" class="ui-draggable ui-draggable-handle form-control" size="8" onclick="detallepersonalrol()">
                                  
                                  {% for p in personal %}
                                  <option value="{{p.id}}">{{p}}</option>}
                                  

                                  {% endfor %}
                              </select>
                            </div>
                        </div>
                        

                        
                    </div>
                </div>
                



            </div>
            <div class="col-md-8 col-lg-8">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-inverse">
                            <div class="panel-heading">
                                <div class="form-group row">
                                    <div class="col-md-10">
                                         <h4 class="panel-title" id="name_personal"></h4>
                                    </div>
                                    <div class="col-md-2">
                                        <button type="submit" onclick="guardar_datos_rol()" class="btn btn-xs btn-success" style="margin-top: 5px;">Guardar</button>
                                    </div>
                                    
                                   
                                </div>
                               
                               
                            </div>
                            <div class="panel-body">
                                <div class="form-group row">
                                    <div class="col-md-12">
                                         <div id="calendar"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </form>
</div>


<div id="modal-dialog" class="modal fade" role="dialog">

</div>
    
{% endblock content %}
{% block scripts %}
<script type='text/javascript' src="{% static "assets/plugins/moment/moment.min.js" %}"></script>
 <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/bootstrap/main.min.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/list/main.min.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/locales/es.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/timegrid/main.min.js" ></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/interaction/main.min.js"></script>


<script src="/static/cronograma.js"></script>

<!-- <script src="/static/fullcalendar.min.js"></script> -->

<script>

    inicializar_calendar()


/*
$("#calendar1").fullCalendar({
    
events: events,
dayClick: function(date, jsEvent, view) {

id_turno=document.getElementById("id_turno");
console.log(date.format())
personal=document.getElementById("id_personal");

console.log(personal.value)
 
var temp={id:id_turno , title: id_turno.options[id_turno.selectedIndex].text, start: date.format()};

events.push(temp);

$("#calendar").fullCalendar( "renderEvent", temp, true );
}
});*/



</script>
{% endblock scripts %}

app/rrhh/templates/rrhh/rol_list.html
{% extends 'base.html' %}

{% load static %}


{% block css %}

<link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/switchery/switchery.css" %}" rel="stylesheet">

<link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet">
    
{% endblock %}

{% block content %}
    <div class="col-md-12 col-lg-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    
                        <div class="pull-right">
                         

                            <a onclick="return abrir_modal('{% url 'rrhh:rol_crear' %}')" class="btn btn btn-primary btn-xs">Crear</a>
                             
                        </div>
                        
                    
                    <h4 class="panel-title">Rol Personal</h4>

                </div>
                <div class="panel-body">

                        <div class="table-responsive">
                            <table class="table table-condensed table-bordered table-hover dataTables-example" style="width:100%">
                                <thead>
                                    <tr>

                                        <th>#</th>
                                        <th>Area</th>
                                        <th>Mes</th>
                                        <th>Año</th>
                                        <th>Responsable</th>
                                        <th>Estado</th>
                                        <th>Accion</th>

                                    </tr>
                                </thead>
                                <tbody>
                                   {% for r in rol %}
                                   <tr class="gradeX">

                                    <td>{{r.id }}</td>
                                    <td>{{r.area}}</td>
                                    <td>{{r.get_mes_display}}</td>
                                    <td>{{r.anio}}</td>
                                    <td>{{r.responsable}}</td>
                                    {% if r.estado == '1' %}
                                    <td><span class="label label-success">{{r.get_estado_display}}</span></td>
                                    {% elif r.estado == '2' %}
                                     <td><span class="label label-warning">{{r.get_estado_display}}</span></td>
                                    {% endif %}
                                    <td class="center">
                                        <a class="btn btn-xs btn-primary" href="{% url 'rrhh:detalle_rol_form' r.id %}" title="Calendario"><i class="far fa-lg fa-calendar-alt" ></i></a>
                                    </td>


                                </tr>

                                {% endfor %}

                            </tbody>

                        </table>
                    </div>
                </div>
            </div>

    </div>

<div id="modal-dialog" class="modal fade" data-keyboard="false" data-backdrop="static" role="dialog">

</div>
    
{% endblock content %}

{% block scripts %}
<script src="{% static "assets/plugins/DataTables/media/js/jquery.dataTables.js" %}"></script>
<script src="{% static "assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js" %}"></script>
<script src="{% static "assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js" %}"></script>



<script>
   $(document).ready(function(){
    $('.dataTables-example').DataTable();
      
    });
</script>
{% endblock scripts %}