app/acceso/urls.py
from django.urls import path, include
from .views import *

app_name = 'acceso'

urlpatterns = [

    path('usuario_list/', usuario_list, name='usuario_list'),
    path('login/', inicio, name='login'),
    path('usuario_crear/<int:id>', usuario_crear, name='usuario_crear'),
    path('acceso/', acceso, name='acceso'),
    path('logout/', logout, name='logout'),

   









    
]

app/asistencia/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name='asistencia'

urlpatterns = [
    
    path('asistencia_form/', asistencia_form,name='asistencia_form'),
    path('asistencia_list/', asistencia_list,name='asistencia_list'),
    path('reporte_form/', reporte_asistencia,name='reporte_form')


]

app/maestro/urls.py
from django.urls import path, include
from .views import *

app_name = 'maestro'

urlpatterns = [
    path('tipo_documento_list/', tipo_documento_list, name='tipo_documento_list'),
    path('tipo_documento_crear/', tipo_documento_crear, name='tipo_documento_crear'),
    path('tipo_documento_update/<int:id>', tipo_documento_update, name='tipo_documento_update'),

    path('cargo_list/', cargo_list, name='cargo_list'),
    path('cargo_crear/', cargo_crear, name='cargo_crear'),
    path('cargo_update/<int:id>', cargo_update, name='cargo_update'),

    path('estado_civil_list/', estado_civil_list, name='estado_civil_list'),
    path('estado_civil_crear/', estado_civil_crear, name='estado_civil_crear'),
    path('estado_civil_update/<int:id>', estado_civil_update, name='estado_civil_update'),

    path('area_list/', area_list, name='area_list'),
    path('areas_crear/', areas_crear, name='areas_crear'),
    path('areas_update/<int:id>', areas_update, name='areas_update'),









    
]

app/rrhh/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name='rrhh'

urlpatterns = [
    path('personal_list/', personal_list, name='personal_list'),
    path('personal_crear/', personal_crear, name='personal_crear'),
    path('personal_update/<int:id>', personal_update, name='personal_update'),

    path('rol_list/', rol_list, name='rol_list'),
    path('rol_crear/', rol_crear, name='rol_crear'),

    path('detalle_rol_form/<int:id>', detalle_rol_form, name='detalle_rol_form'),

    path('guardar_foto/<int:id_detalle>',guardar_foto, name='guardar_foto'),

    path('permiso_list/', permiso_list, name='permiso_list'),
    path('permiso_form/', permiso_form, name='permiso_form'),



    

]

controlasistencia/urls.py
from django.contrib import admin
from django.urls import path, include
from app.maestro import urls
from app.rrhh import urls
from app.acceso import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('maestro/',include('app.maestro.urls')),
    path('rrhh/',include('app.rrhh.urls')),
    path('rrhh/api/',include('app.rrhh.api.urls')),
    path('asistencia/',include('app.asistencia.urls')),
    path('acceso/',include('app.acceso.urls')),
    path('acceso/api/',include('app.acceso.api.urls')),


]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8" />
	    

					<title>CONTROL DE ASISTENCIA</title>
			<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />

	<!-- ================== BEGIN BASE CSS STYLE ================== -->
	
	<link href="{% static 'assets/plugins/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/bootstrap/4.1.0/css/bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/font-awesome/5.0/css/fontawesome-all.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/plugins/animate/animate.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/css/default/style.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/css/default/style-responsive.min.css' %}" rel="stylesheet" />
	<link href="{% static 'assets/css/default/theme/default.css' %}" rel="stylesheet" id="theme" />
	<link href="{% static 'assets/plugins/ionicons/css/ionicons.min.css' %}" rel="stylesheet" id="theme" />
	<link href="{% static 'eigen/css/estilo.css' %}" rel="stylesheet" id="theme" />
	
	<!-- ================== END BASE CSS STYLE ================== -->

	<!-- ================== BEGIN BASE JS ================== -->
	<script src="{% static 'assets/plugins/pace/pace.min.js' %}"></script>
	<!-- ================== END BASE JS ================== -->

	<title>{% block title %}{% endblock title %}</title>

    {% block css %}

    {% endblock css %}

</head>
<body>
	<!-- begin #page-loader -->
	<div id="page-loader" class="fade show"><span class="spinner"></span></div>
	<!-- end #page-loader -->

	<!-- begin #page-container -->
	<div id="page-container" class="page-container fade page-without-sidebar page-header-fixed page-with-top-menu">
    
    <!-- begin #header -->
		<div id="header" class="header navbar-default">
			<!-- begin navbar-header -->
			<div class="navbar-header">
				<a href="#" class="navbar-brand"><img src="/static/assets/img/logo.jpeg" style="width: 30%;height: 110%"></span> <b>SISTEMA DE CONTROL DE ASISTENCIA{{datogeneral.persona.centrocosto.unidadejecutora.abreviado}}</b></a>
				<button type="button" class="navbar-toggle" data-click="top-menu-toggled">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

            <ul class="navbar-nav navbar-right">
				<li class="dropdown navbar-user">
					<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                        {{ datogeneral.persona }}
                        <img src="" alt="" />
                        <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li class="arrow"></li>
						<li><a href="javascript:;">Edit Profile</a></li>
						<li class="divider"></li>
						<li><a href="{% url 'acceso:logout' %}">Salir</a></li>
					</ul>
				</li>
			</ul>
			<!-- end header navigation right -->
		</div>
		<!-- end #header -->
		<!-- begin #top-menu -->

            {% include 'menu.html' %}
   
        <div id="content" class="content">
        {% block content %}

	    {% endblock content %}
        </div>
    </div>
	<!-- end page container -->
	<!-- ================== BEGIN BASE JS ================== -->
	<script src="{% static 'assets/plugins/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'assets/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
	<script src="{% static 'assets/plugins/bootstrap/4.1.0/js/bootstrap.bundle.min.js' %}"></script>
	<!--[if lt IE 9]>
		<script src="../assets/crossbrowserjs/html5shiv.js"></script>
		<script src="../assets/crossbrowserjs/respond.min.js"></script>
		<script src="../assets/crossbrowserjs/excanvas.min.js"></script>
	<![endif]-->
	<script src="{% static 'assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
	<script src="{% static 'assets/plugins/js-cookie/js.cookie.js' %}"></script>
	<!--<script src="{% static 'assets/js/theme/default.min.js' %}"></script>-->
	<script src="{% static 'assets/js/apps.min.js' %}"></script>
	<!-- ================== END BASE JS ================== -->

	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
    <script src="{% static 'assets/plugins/d3/3.5.2/d3.min.js' %}"></script>
    <!--<script src="{% static 'assets/plugins/nvd3/build/nv.d3.js' %}"></script>
    <script src="{% static 'assets/plugins/jquery-jvectormap/jquery-jvectormap.min.js' %}"></script>
    <script src="{% static 'assets/plugins/jquery-jvectormap/jquery-jvectormap-world-merc-en.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap-calendar/js/bootstrap_calendar.min.js' %}"></script>
	<script src="{% static 'assets/plugins/gritter/js/jquery.gritter.js' %}"></script>
	<script src="{% static 'assets/js/demo/dashboard-v2.min.js' %}"></script>-->
	<script src="{% static 'assets/plugins/select2/dist/js/select2.min.js' %}"></script>
	<!-- ================== END PAGE LEVEL JS ================== -->
    <!-- ================== ADMISION ================== -->
	{% block scripts %}
	{% endblock scripts %}
	<script>
    function abrir_modal(url)
	{
		console.log(url)
        $('#modal-dialog').load(url, function()
        {
            $(this).modal('show');
        });
        return false;
	}
    $(document).ready(function() {
        App.init();
    });
</script>
</body>
</html>

templates/menu.html
<div id="top-menu" class="top-menu" style="background-color: #9ac61b;color:white">
    <!-- begin top-menu nav -->
    <ul class="nav" style="color: white;">
        
       
       {% for foo in datogeneral.usergrupo %}
             {% if foo.group_id == 3 %}
              
           
                <li class="has-sub">
                    <a href="javascript:;">
                        <b class="caret"></b>
                        <i class="fa fa-cogs"></i>
                        <span>CONFIGURACION</span>
                    </a>
                    <ul class="sub-menu">
                        
                        <li><a href="{% url 'maestro:tipo_documento_list' %}">Tipo Documento</a></li>
                        
                        <li><a href="{% url 'maestro:cargo_list' %}">Cargo</a></li>
                        
                        <li><a href="{% url 'maestro:estado_civil_list' %}">Estado Civil</a></li>
                        
                        <li><a href="{% url 'maestro:area_list' %}">Areas</a></li>
                       
                      
                    </ul>
                </li>
                {% endif %}
          
                 {% if foo.group_id == 2  %}
           
                        {% if request.user.is_superuser == True%}
                            <li class="has-sub">
                                <a href="javascript:;">
                                    <b class="caret"></b>
                                    <i class="fa fa-users"></i>
                                    <span>RRHH</span>
                                </a>
                                <ul class="sub-menu">
                                    
                                        <li><a href="{% url 'rrhh:personal_list' %}">Personal</a></li>
                                  
                                        
                                
                                </ul>
                            </li>
                            <li class="has-sub">
                            <a href="javascript:;">
                                <b class="caret"></b>
                                <i class="fa fa-calendar-alt"></i>
                                <span>CRONOGRAMA</span>
                            </a>
                            <ul class="sub-menu">
                                
                                    <li><a href="{% url 'rrhh:rol_list' %}">Rol Personal</a></li>
                              
                                    <li><a href="{% url 'rrhh:permiso_list' %}">Permisos</a></li>
                                   
                                
                            </ul>
                        </li>

                    
                        {% else %}
              
                            <li class="has-sub">
                                <a href="javascript:;">
                                    <b class="caret"></b>
                                    <i class="fa fa-calendar-alt"></i>
                                    <span>CRONOGRAMA</span>
                                </a>
                                <ul class="sub-menu">
                                    
                                        <li><a href="{% url 'rrhh:rol_list' %}">Rol Personal</a></li>
                                  
                                        <li><a href="{% url 'rrhh:permiso_list' %}">Permisos</a></li>
                                       
                                    
                                </ul>
                            </li>
                            {% endif %}
                    {% endif %}
                    {% if foo.group_id == 1 %}
                    <li class="has-sub">
                        <a href="javascript:;">
                            <b class="caret"></b>
                            <i class="fa fa-calendar-alt"></i>
                            <span>ASISTENCIA</span>
                        </a>
                        <ul class="sub-menu">
                            
                                <li><a href="{% url 'asistencia:asistencia_form' %}">Asistencia</a></li>
                                <li><a href="{% url 'asistencia:asistencia_list' %}">Reporte Asistencia</a></li>
                          
                               
                               
                            
                        </ul>
                    </li>
                    {% endif %}
                     {% if foo.group_id == 4%}
        <li class="has-sub">
                    <a href="javascript:;">
                        <b class="caret"></b>
                        <i class="fa fa-user-plus"></i>
                        <span>Usuario</span>
                    </a>
                    <ul class="sub-menu">
                        
                        <li><a href="{% url 'acceso:usuario_list' %}">Lista Usuario</a></li>
                        
                      
                       
                      
                    </ul>
            </li>
        {% endif %}
        {% endfor %}
       
        <li class="menu-control menu-control-left">
            <a href="javascript:;" data-click="prev-menu"><i class="fa fa-angle-left"></i></a>
        </li>
        <li class="menu-control menu-control-right">
            <a href="javascript:;" data-click="next-menu"><i class="fa fa-angle-right"></i></a>
        </li>
    </ul>

    <!-- end top-menu nav -->
</div>