app/maestro/urls.py
from django.urls import path, include
from .views import *

app_name = 'maestro'

urlpatterns = [
    path('tipo_documento_list/', tipo_documento_list, name='tipo_documento_list'),
    path('tipo_documento_crear/', tipo_documento_crear, name='tipo_documento_crear'),
    path('tipo_documento_update/<int:id>', tipo_documento_update, name='tipo_documento_update'),

    path('cargo_list/', cargo_list, name='cargo_list'),
    path('cargo_crear/', cargo_crear, name='cargo_crear'),
    path('cargo_update/<int:id>', cargo_update, name='cargo_update'),

    path('estado_civil_list/', estado_civil_list, name='estado_civil_list'),
    path('estado_civil_crear/', estado_civil_crear, name='estado_civil_crear'),
    path('estado_civil_update/<int:id>', estado_civil_update, name='estado_civil_update'),

    path('area_list/', area_list, name='area_list'),
    path('areas_crear/', areas_crear, name='areas_crear'),
    path('areas_update/<int:id>', areas_update, name='areas_update'),









    
]

controlasistencia/urls.py
from django.contrib import admin
from django.urls import path, include
from app.maestro import urls
from app.rrhh import urls
from app.acceso import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('maestro/',include('app.maestro.urls')),
    path('rrhh/',include('app.rrhh.urls')),
    path('rrhh/api/',include('app.rrhh.api.urls')),
    path('asistencia/',include('app.asistencia.urls')),
    path('acceso/',include('app.acceso.urls')),
    path('acceso/api/',include('app.acceso.api.urls')),


]

app/maestro/models.py
from django.db import models

# Create your models here.

class TipoDocumento(models.Model):

	descripcion=models.CharField(max_length=100)
	abreviado=models.CharField(max_length=10)

	def __str__(self):

		return self.descripcion

class EstadoCivil(models.Model):
    descripcion = models.CharField(max_length=30)
    abreviado = models.CharField(max_length=5)


    def __str__(self):
        return '{}'.format(self.descripcion)

class Empresa(models.Model):
	descripcion=models.CharField(max_length=150)
	direccion=models.CharField(max_length=50)
	telefono=models.CharField(max_length=10)

class Turno(models.Model):

	descripcion=models.CharField(max_length=20)
	hora_inicio=models.TimeField()
	hora_fin=models.TimeField()
	abreviado=models.CharField(max_length=4)

	




class Areas(models.Model):

	ESTADO=[
		('1','ACTIVO'),
		('2','INACTIVO')

	]

	descripcion=models.CharField(max_length=50)
	estado=models.CharField(max_length=1, choices=ESTADO)

	def __str__(self):

		return self.descripcion

class Cargo(models.Model):

	ESTADO=[

		('1','ACTIVO'),
		('2','INACTIVO')

	]
	descripcion=models.CharField(max_length=50)
	estado=models.CharField(max_length=1, choices=ESTADO)

	def __str__(self):

		return self.descripcion

app/maestro/forms.py
from django import forms

from .models import *

class TipoDocumentoForm(forms.ModelForm):
    class Meta:
        model = TipoDocumento
        fields=[
            'descripcion',
            'abreviado',
            
        ]

        labels={
            'descripcion':'Descripcion',
            'abreviado':'Abreviado',
            
        }

        widgets={
            'descripcion':forms.TextInput(attrs={'class':'form-control'}),
            'abreviado':forms.TextInput(attrs={'class':'form-control'}),
            

        }



class CargoForm(forms.ModelForm):
    class Meta:
        model = Cargo
        fields=[
            'descripcion',
            'estado',
            
        ]

        labels={
            'descripcion':'Descripcion',
            'estado':'Estado',
            
        }

        widgets={
            'descripcion':forms.TextInput(attrs={'class':'form-control'}),
            'estado':forms.Select(attrs={'class':'form-control'}),
            

        }


class EstadoCivilForm(forms.ModelForm):
    class Meta:
        model = EstadoCivil
        fields=[
            'descripcion',
            'abreviado',
            
        ]

        labels={
            'descripcion':'Descripcion',
            'abreviado':'Abreviado',
            
        }

        widgets={
            'descripcion':forms.TextInput(attrs={'class':'form-control'}),
            'abreviado':forms.TextInput(attrs={'class':'form-control'}),
            

        }


class AreasForm(forms.ModelForm):
    class Meta:
        model = Areas
        fields=[
            'descripcion',
            'estado',
            
        ]

        labels={
            'descripcion':'Descripcion',
            'estado':'Estado',
            
        }

        widgets={
            'descripcion':forms.TextInput(attrs={'class':'form-control'}),
            'estado':forms.Select(attrs={'class':'form-control'}),
            

        }

app/maestro/views.py
from django.shortcuts import render, redirect
from app.maestro.forms import *
from app.rrhh.models import *
from django.http import HttpResponse
# Create your views here.
from django.core.files.base import ContentFile
from django.contrib.auth.decorators import login_required
from functools import wraps
from django.contrib.auth.models import *

from app.acceso.models import *
from django.core.files.base import ContentFile
from django.contrib.auth.decorators import login_required
from functools import wraps
from django.contrib.auth.models import *

def check_group(group_name):
    def _check_group(view_func):
        @wraps(view_func)
        def wrapper(request, *args, **kwargs):
            if request.user.is_anonymous:
                return redirect('acceso:acceso')
            if not (request.user.groups.filter(name=group_name).exists() or request.user.is_superuser):
                return redirect('acceso:usuario_list')
            return view_func(request, *args, **kwargs)
        return wrapper
    return _check_group

def datosgenerales(request):
    try:
        modulo = 'maestro'
        personal = Personal.objects.get(usuario=request.user.id)
        estado = personal.estado
   
        try:
            usergrupo = GrupoUser.objects.filter(user_id=personal.usuario_id)
            
            #menu = Menu.objects.filter(grupo_id=2)
            #print(menu)
            
            contexto = {'estado': estado, 'persona': personal,'usergrupo':usergrupo,'modulo':modulo}
            
        except GrupoUser.DoesNotExist:
            pass
    except Personal.DoesNotExist:
        return HttpResponse('Logeado Pero no estas asignado como Personal')
    return contexto





def tipo_documento_list(request):

	tipo_documento=TipoDocumento.objects.all()

	return render(request,'maestro/tipo_documento_list.html',{'tipo_documento':tipo_documento,'datogeneral':datosgenerales(request)})

def tipo_documento_crear(request):

	if request.method=='POST':

		form=TipoDocumentoForm(request.POST)

		if form.is_valid():

			form.save()

			return redirect('maestro:tipo_documento_list')
		else:

			return HttpResponse(form.errors)

	
	else:
		form=TipoDocumentoForm
		return render(request,'maestro/tipo_documento_form.html',{'form':form})

def tipo_documento_update(request,id):
    tipo_documento = TipoDocumento.objects.get(id=id)

    if request.method=='POST':
        form = TipoDocumentoForm(request.POST,instance=tipo_documento)
        if form.is_valid():
            form.save()
            return redirect('maestro:tipo_documento_list')
        else:
            return HttpResponse(form.errors)

    else:
        form = TipoDocumentoForm(instance=tipo_documento)

        return render(request,'maestro/tipo_documento_form.html',{'form':form,'tipo_documento':tipo_documento,'datogeneral':datosgenerales(request)})


def cargo_list(request):

	cargo=Cargo.objects.all()

	return render(request,'maestro/cargo_list.html',{'cargo':cargo,'datogeneral':datosgenerales(request)})


def cargo_crear(request):

	if request.method=='POST':

		form=CargoForm(request.POST)

		if form.is_valid():

			form.save()

			return redirect('maestro:cargo_list')
		else:

			return HttpResponse(form.errors)

	
	else:
		form=CargoForm
		return render(request,'maestro/cargo_form.html',{'form':form,'datogeneral':datosgenerales(request)})


def cargo_update(request,id):
    cargo = Cargo.objects.get(id=id)

    if request.method=='POST':
        form = CargoForm(request.POST,instance=cargo)
        if form.is_valid():
            form.save()
            return redirect('maestro:cargo_list')
        else:
            return HttpResponse(form.errors)

    else:
        form = CargoForm(instance=cargo)

        return render(request,'maestro/cargo_form.html',{'form':form,'cargo':cargo,'datogeneral':datosgenerales(request)})


def estado_civil_list(request):

	estado_civil=EstadoCivil.objects.all()

	return render(request,'maestro/estado_civil_list.html',{'estado_civil':estado_civil,'datogeneral':datosgenerales(request)})

def estado_civil_crear(request):

	if request.method=='POST':

		form=EstadoCivilForm(request.POST)

		if form.is_valid():

			form.save()

			return redirect('maestro:estado_civil_list')
		else:

			return HttpResponse(form.errors)

	
	else:
		form=EstadoCivilForm
		return render(request,'maestro/estado_civil_form.html',{'form':form,'datogeneral':datosgenerales(request)})


def estado_civil_update(request,id):
    estado_civil = EstadoCivil.objects.get(id=id)

    if request.method=='POST':
        form = EstadoCivilForm(request.POST,instance=estado_civil)
        if form.is_valid():
            form.save()
            return redirect('maestro:estado_civil_list')
        else:
            return HttpResponse(form.errors)

    else:
        form = EstadoCivilForm(instance=estado_civil)

        return render(request,'maestro/estado_civil_form.html',{'form':form,'estado_civil':estado_civil,'datogeneral':datosgenerales(request)})


def area_list(request):

	area=Areas.objects.all()

	return render(request,'maestro/area_list.html',{'area':area,'datogeneral':datosgenerales(request)})

def areas_crear(request):

	if request.method=='POST':

		form=AreasForm(request.POST)

		if form.is_valid():

			form.save()

			return redirect('maestro:area_list')
		else:

			return HttpResponse(form.errors)

	
	else:
		form=AreasForm
		return render(request,'maestro/area_form.html',{'form':form,'datogeneral':datosgenerales(request)})


def areas_update(request,id):
    areas = Areas.objects.get(id=id)

    if request.method=='POST':
        form = AreasForm(request.POST,instance=areas)
        if form.is_valid():
            form.save()
            return redirect('maestro:area_list')
        else:
            return HttpResponse(form.errors)

    else:
        form = AreasForm(instance=areas)

        return render(request,'maestro/area_form.html',{'form':form,'areas':areas,'datogeneral':datosgenerales(request)})

app/maestro/templates/maestro/area_form.html
{% extends 'base.html' %}

{% load static %}


{% block css %}

<link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/switchery/switchery.css" %}" rel="stylesheet">

<link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet">
    
{% endblock %}

{% block content %}
    <div class="col-md-12 col-lg-12">
        

            
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    {% if areas %}
                     
                    <form method="POST" action="{% url 'maestro:areas_update' areas.id %}">
                        <h4 class="panel-title">Actualizar Areas</h4>
                    {% else %}

                    <form method="POST" action="{% url 'maestro:areas_crear' %}">
                        <h4 class="panel-title">Crear Areas</h4>

                    {% endif %}

                    {% csrf_token %}
                        <div class="pull-right" style="margin-top: -12px;">
                            <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
                             
                        </div>


                </div>
                <div class="panel-body">
                    <div class="form-group row">
                        <div class="col-md-2">{{form.descripcion.label_tag}}</div>
                        <div class="col-md-4">{{form.descripcion}}</div>
                        <div class="col-md-2">{{form.estado.label_tag}}</div>
                        <div class="col-md-4">{{form.estado}}</div>
                       
                    </div>
                   

                       
                </div>
            </form>
            </div>
       
    </div>


    
{% endblock content %}

{% block scripts %}



{% endblock scripts %}

app/maestro/templates/maestro/area_list.html
{% extends 'base.html' %}

{% load static %}


{% block css %}

<link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/switchery/switchery.css" %}" rel="stylesheet">

<link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet">
    
{% endblock %}

{% block content %}
    <div class="col-md-12 col-lg-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    
                        <div class="pull-right">
                            <a href="{% url 'maestro:areas_crear' %}" class="btn btn-sm btn-primary">Crear</a>
                             
                        </div>
                        
                    
                    <h4 class="panel-title">Lista Areas</h4>

                </div>
                <div class="panel-body">

                        <div class="table-responsive">
                            <table class="table table-condensed table-bordered table-hover dataTables-example" style="width:100%">
                                <thead>
                                    <tr>

                                        <th>#</th>
                                        <th>Descripcion</th>
                                        <th>Estado</th>
                                        <th>Accion</th>

                                    </tr>
                                </thead>
                                <tbody>
                                   {% for a in area %}
                                   <tr class="gradeX">

                                    <td>{{a.id }}</td>
                                    <td>{{a.descripcion}}</td>
                                    {% if a.estado == '1' %}
                                    <td><span class="label label-success">{{a.get_estado_display }}</span></td>
                                    {% else %}
                                    <td><span class="label label-danger">{{a.get_estado_display }}</span></td>

                                    {% endif %}

                                    <td class="center">
                                        <a class="btn btn-xs btn-primary" href="{% url 'maestro:areas_update' a.id %}" title="Editar"><i class="fas fa-lg fa-edit"></i></a>
                                           
                                    </td>


                                </tr>

                                {% endfor %}

                            </tbody>

                        </table>
                    </div>
                </div>
            </div>

    </div>

<div id="modal-dialog" class="modal fade" role="dialog">

</div>
    
{% endblock content %}

{% block scripts %}
<script src="{% static "assets/plugins/DataTables/media/js/jquery.dataTables.js" %}"></script>
<script src="{% static "assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js" %}"></script>
<script src="{% static "assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js" %}"></script>



<script>
   $(document).ready(function(){
    $('.dataTables-example').DataTable();
      
    });
</script>
{% endblock scripts %}

app/maestro/templates/maestro/cargo_form.html
{% extends 'base.html' %}

{% load static %}


{% block css %}

<link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/switchery/switchery.css" %}" rel="stylesheet">

<link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet">
    
{% endblock %}

{% block content %}
    <div class="col-md-12 col-lg-12">
        

            
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    {% if cargo %}
                     
                    <form method="POST" action="{% url 'maestro:cargo_update' cargo.id %}">
                        <h4 class="panel-title">Actualizar Cargo</h4>
                    {% else %}

                    <form method="POST" action="{% url 'maestro:cargo_crear' %}">
                        <h4 class="panel-title">Crear Cargo</h4>

                    {% endif %}

                    {% csrf_token %}
                        <div class="pull-right" style="margin-top: -12px;">
                            <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
                             
                        </div>


                </div>
                <div class="panel-body">
                    <div class="form-group row">
                        <div class="col-md-2">{{form.descripcion.label_tag}}</div>
                        <div class="col-md-4">{{form.descripcion}}</div>
                        <div class="col-md-2">{{form.estado.label_tag}}</div>
                        <div class="col-md-4">{{form.estado}}</div>
                       
                    </div>
                   

                       
                </div>
            </form>
            </div>
       
    </div>


    
{% endblock content %}

{% block scripts %}



{% endblock scripts %}

app/maestro/templates/maestro/cargo_list.html
{% extends 'base.html' %}

{% load static %}


{% block css %}

<link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/switchery/switchery.css" %}" rel="stylesheet">

<link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet">
    
{% endblock %}

{% block content %}
    <div class="col-md-12 col-lg-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    
                        <div class="pull-right">
                            <a href="{% url 'maestro:cargo_crear' %}" class="btn btn-sm btn-primary">Crear</a>
                             
                        </div>
                        
                    
                    <h4 class="panel-title">Lista Cargo</h4>

                </div>
                <div class="panel-body">

                        <div class="table-responsive">
                            <table class="table table-condensed table-bordered table-hover dataTables-example" style="width:100%">
                                <thead>
                                    <tr>

                                        <th>#</th>
                                        <th>Descripcion</th>
                                        <th>Estado</th>
                                        <th>Accion</th>

                                    </tr>
                                </thead>
                                <tbody>
                                   {% for c in cargo %}
                                   <tr class="gradeX">

                                    <td>{{c.id }}</td>
                                    <td>{{c.descripcion}}</td>
                                    {% if c.estado == '1' %}
                                    <td><span class="label label-success">{{c.get_estado_display }}</span></td>
                                    {% else %}
                                    <td><span class="label label-danger">{{c.get_estado_display }}</span></td>

                                    {% endif %}

                                    <td class="center">
                                        <a class="btn btn-xs btn-primary" href="{% url 'maestro:cargo_update' c.id %}" title="Editar"><i class="fas fa-lg fa-edit"></i></a>
                                           
                                    </td>


                                </tr>

                                {% endfor %}

                            </tbody>

                        </table>
                    </div>
                </div>
            </div>

    </div>

<div id="modal-dialog" class="modal fade" role="dialog">

</div>
    
{% endblock content %}

{% block scripts %}
<script src="{% static "assets/plugins/DataTables/media/js/jquery.dataTables.js" %}"></script>
<script src="{% static "assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js" %}"></script>
<script src="{% static "assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js" %}"></script>



<script>
   $(document).ready(function(){
    $('.dataTables-example').DataTable();
      
    });
</script>
{% endblock scripts %}

app/maestro/templates/maestro/estado_civil_form.html
{% extends 'base.html' %}

{% load static %}


{% block css %}

<link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/switchery/switchery.css" %}" rel="stylesheet">

<link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet">
    
{% endblock %}

{% block content %}
    <div class="col-md-12 col-lg-12">
        

            
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    {% if estado_civil %}
                     
                    <form method="POST" action="{% url 'maestro:estado_civil_update' estado_civil.id %}">
                        <h4 class="panel-title">Actualizar Estado Civil</h4>
                    {% else %}

                    <form method="POST" action="{% url 'maestro:estado_civil_crear' %}">
                        <h4 class="panel-title">Crear Estado Civil</h4>

                    {% endif %}

                    {% csrf_token %}
                        <div class="pull-right" style="margin-top: -12px;">
                            <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
                             
                        </div>


                </div>
                <div class="panel-body">
                    <div class="form-group row">
                        <div class="col-md-2">{{form.descripcion.label_tag}}</div>
                        <div class="col-md-4">{{form.descripcion}}</div>
                        <div class="col-md-2">{{form.abreviado.label_tag}}</div>
                        <div class="col-md-4">{{form.abreviado}}</div>
                       
                    </div>
                   

                       
                </div>
            </form>
            </div>
       
    </div>


    
{% endblock content %}

{% block scripts %}



{% endblock scripts %}

app/maestro/templates/maestro/estado_civil_list.html
{% extends 'base.html' %}

{% load static %}


{% block css %}

<link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/switchery/switchery.css" %}" rel="stylesheet">

<link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet">
    
{% endblock %}

{% block content %}
    <div class="col-md-12 col-lg-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    
                        <div class="pull-right">
                            <a href="{% url 'maestro:estado_civil_crear' %}" class="btn btn-sm btn-primary">Crear</a>
                             
                        </div>
                        
                    
                    <h4 class="panel-title">Lista Estado Civil</h4>

                </div>
                <div class="panel-body">

                        <div class="table-responsive">
                            <table class="table table-condensed table-bordered table-hover dataTables-example" style="width:100%">
                                <thead>
                                    <tr>

                                        <th>#</th>
                                        <th>Descripcion</th>
                                        <th>Abreviado</th>
                                        <th>Accion</th>

                                    </tr>
                                </thead>
                                <tbody>
                                   {% for e in estado_civil %}
                                   <tr class="gradeX">

                                    <td>{{e.id }}</td>
                                    <td>{{e.descripcion}}</td>
                                    <td>{{e.abreviado}}</td>
                                    <td class="center">
                                        <a class="btn btn-xs btn-primary" href="{% url 'maestro:estado_civil_update' e.id %}" title="Editar"><i class="fas fa-lg fa-edit"></i></a>
                                           
                                    </td>


                                </tr>

                                {% endfor %}

                            </tbody>

                        </table>
                    </div>
                </div>
            </div>

    </div>

<div id="modal-dialog" class="modal fade" role="dialog">

</div>
    
{% endblock content %}

{% block scripts %}
<script src="{% static "assets/plugins/DataTables/media/js/jquery.dataTables.js" %}"></script>
<script src="{% static "assets/plugins/DataTables/media/js/dataTables.bootstrap.min.js" %}"></script>
<script src="{% static "assets/plugins/DataTables/extensions/Responsive/js/dataTables.responsive.min.js" %}"></script>



<script>
   $(document).ready(function(){
    $('.dataTables-example').DataTable();
      
    });
</script>
{% endblock scripts %}

app/maestro/templates/maestro/tipo_documento_form.html
{% extends 'base.html' %}

{% load static %}


{% block css %}

<link href="{% static "assets/plugins/DataTables/media/css/dataTables.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/DataTables/extensions/Responsive/css/responsive.bootstrap.min.css" %}" rel="stylesheet" />

<link href="{% static "assets/plugins/switchery/switchery.css" %}" rel="stylesheet">

<link href="{% static "assets/plugins/select2/dist/css/select2.min.css" %}" rel="stylesheet">
    
{% endblock %}

{% block content %}
    <div class="col-md-12 col-lg-12">
        

            
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    {% if tipo_documento %}
                     
                    <form method="POST" action="{% url 'maestro:tipo_documento_update' tipo_documento.id %}">
                        <h4 class="panel-title">Actualizar Tipo Documento</h4>
                    {% else %}

                    <form method="POST" action="{% url 'maestro:tipo_documento_crear' %}">
                        <h4 class="panel-title">Crear Tipo Documento</h4>

                    {% endif %}

                    {% csrf_token %}
                        <div class="pull-right" style="margin-top: -12px;">
                            <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
                             
                        </div>


                </div>
                <div class="panel-body">
                    <div class="form-group row">
                        <div class="col-md-2">{{form.descripcion.label_tag}}</div>
                        <div class="col-md-4">{{form.descripcion}}</div>
                        <div class="col-md-2">{{form.abreviado.label_tag}}</div>
                        <div class="col-md-4">{{form.abreviado}}</div>
                       
                    </div>
                   

                       
                </div>
            </form>
            </div>
       
    </div>


    
{% endblock content %}

{% block scripts %}



{% endblock scripts %}